spring:
  jmx:
    default-domain: qipai_fangpaomajiang
  data:
    mongodb:
      #uri: mongodb://localhost:27017/qipai_fangpaomajiang
        
  cloud:
    stream:
      kafka:
        binder:
          #brokers: localhost:9092
          #zk-nodes: localhost:2181
          brokers: 172.16.21.51:9092
          zk-nodes: 172.16.21.51:2181
          minPartitionCount: 1
          autoCreateTopics: true
          autoAddPartitions: false
        bindings:
          fangpaoMajiangGame:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          fangpaoMajiangResult:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          memberGoldsAccounting:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
      bindings:
        fangpaoMajiangGame:
          destination: fangpaoMajiangGame
          contentType: application/json
          producer:
            partitionCount: 1
        fangpaoMajiangResult:
          destination: fangpaoMajiangResult
          contentType: application/json
          producer:
            partitionCount: 1
        memberGoldsAccounting:
          destination: memberGoldsAccounting
          contentType: application/json
          producer:
            partitionCount: 1
        members:
          destination: members
          group: qipai-fangpaomajiang
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        fangpaoGameRoom:
          destination: fangpaoGameRoom
          group: qipai-fangpaomajiang
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        memberGolds:
          destination: memberGolds
          group: qipai-fangpaomajiang
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
      
server:
  port: 2002
  
filepath:
  snapshotFileBasePath: /data/app/qipai_fangpaomajiang/server1/snapshot
  jFileBasePath: /data/app/qipai_fangpaomajiang/server1/journal
  
logging:
  config: classpath:spring-log.xml