spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/qipai_dapaomajiang
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          zk-nodes: localhost:2181
          minPartitionCount: 1
          autoCreateTopics: true
          autoAddPartitions: false
        bindings:
          dapaoMajiangGame:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          dapaoMajiangJuResult:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
      bindings:
        dapaoMajiangGame:
          destination: dapaoMajiangGame
          contentType: application/json
          producer:
            partitionCount: 1
        dapaoMajiangJuResult:
          destination: dapaoMajiangJuResult
          contentType: application/json
          producer:
            partitionCount: 1
        members:
          destination: members
          group: qipai_members
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
      
server:
  port: 2002