spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/qipai_fangpaomajiang
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          zk-nodes: localhost:2181
          minPartitionCount: 1
          autoCreateTopics: true
          autoAddPartitions: false
        bindings:
          fangpaoMajiangGame:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
          fangpaoMajiangResult:
            producer:
              configuration:
                request:
                  timeout:
                    ms: 30000
                linger:
                  ms: 5
                batch:
                  size: 16384
      bindings:
        fangpaoMajiangGame:
          destination: fangpaoMajiangGame
          contentType: application/json
          producer:
            partitionCount: 1
        fangpaoMajiangResult:
          destination: fangpaoMajiangResult
          contentType: application/json
          producer:
            partitionCount: 1
        members:
          destination: members
          group: qipai-fangpaomajiang
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
        fangpaoGameRoom:
          destination: fangpaoGameRoom
          group: qipai-fangpaomajiang
          consumer:
            concurrency: 1
            partitioned: false
          contentType: application/json
      
server:
  port: 2002
  
filepath:
  snapshotFileBasePath: /usr/local/app/qipai_fangpaomajiang/server1/snapshot
  jFileBasePath: /usr/local/app/qipai_fangpaomajiang/server1/journal